[[piglit]]
piglit_folder = "/piglit"
profile = "gpu"
process_isolation = true
  [piglit.env]
  PIGLIT_NO_WINDOW = "1"

# Smoke test AFBC-P
[[piglit]]
piglit_folder = "/piglit"
profile = "gpu"
process_isolation = true
include = [ "spec@.*texture" ]
prefix = "afbcp-"
  [piglit.env]
  PIGLIT_NO_WINDOW = "1"
  PAN_MESA_DEBUG = "forcepack"
