/* This is a placeholder file that should be replaced with the contents
 * generated by the rddecompiler from a trace file.
*/
#include "util/macros.h"
#include "decode/rdcompiler-utils.h"
int main(int argc, char **argv)
{
	UNREACHABLE("you forgot to update generate-rd.cc");

	(void)replay_context_init;
	(void)replay_context_finish;
	(void)pkt4;

	return 1;
}
