include:
  - local: 'src/freedreno/ci/gitlab-ci-inc.yml'

.a306-gl:
  extends:
    - .baremetal-deqp-test
    - .a306-test
  variables:
    DEQP_SUITE: freedreno-a306
    FDO_CI_CONCURRENT: 6
  parallel: 5

.a306-piglit:
  extends:
    - .baremetal-deqp-test
    - .a306-test
    - .test-piglit
    - .google-freedreno-manual-rules
  timeout: 40m
  variables:
    DEQP_SUITE: freedreno-a306-piglit
    HWCI_START_WESTON: 1
    TEST_PHASE_TIMEOUT_MINUTES: 35

# Something happened and now this hangchecks and doesn't recover.  Unkown when
# it started.
.a306-piglit-gl:
  extends:
    - .baremetal-deqp-test
    - .a306-test
    - .test-piglit
    - .google-freedreno-manual-rules
  variables:
    BM_KERNEL_EXTRA_ARGS: "msm.num_hw_submissions=1"
    DEQP_SUITE: freedreno-a306-piglit-quick-gl
    FDO_CI_CONCURRENT: 3
    HWCI_START_WESTON: 1

.a306-piglit-shader:
  extends:
    - .baremetal-deqp-test
    - .a306-test
    - .test-piglit
    - .google-freedreno-manual-rules
  variables:
    DEQP_SUITE: freedreno-a306-piglit-quick-shader
    FDO_CI_CONCURRENT: 6
    HWCI_START_WESTON: 1

.a306-traces:
  extends:
    - .google-freedreno-test-traces
    - .a306-test

.a530-gl:
  extends:
    - .baremetal-deqp-test
    - .test-piglit
    - .a530-test
  variables:
    DEQP_SUITE: freedreno-a530
    FDO_CI_CONCURRENT: 3  # if 4, sometimes "deqp-gles31, not enough memory for the allocation" appears
  parallel: 6

.a530-traces:
  extends:
    - .google-freedreno-test-traces
    - .a530-test

.a530-piglit:
  extends:
    - .baremetal-deqp-test
    - .a530-test
    - .test-piglit
    - .google-freedreno-manual-rules
  parallel: 2
  variables:
    DEQP_SUITE: freedreno-a530-piglit
    HWCI_START_WESTON: 1

a618-angle:
  extends:
    - .lava-arm64-test-gl
    - .lava-sc7180-trogdor-kingoftown:arm64
    - .collabora-turnip-manual-rules
    - .test-angle
  variables:
    DEQP_SUITE: tu-angle
    DRIVER_NAME: null  # Don't use freedreno skips

a618-vk:
  extends:
    - .lava-arm64-test-vk
    - .lava-sc7180-trogdor-kingoftown:arm64
    - .collabora-turnip-rules
  parallel: 8
  variables:
    DEQP_SUITE: freedreno-a618-vk
    FLAKES_CHANNEL: "#freedreno-ci"
    MESA_VK_IGNORE_CONFORMANCE_WARNING: 1

a618-vk-full:
  extends:
    - a618-vk
    - .collabora-turnip-manual-rules
  # We use a longer timeout to keep the parallel down so that we don't lock up
  # too many runners for a long time when a dev is trying out at full VK status.
  timeout: 2h
  parallel: 3
  variables:
    DEQP_SUITE: freedreno-a618-vk-full

a618-vk-asan:
  extends:
    - .lava-arm64-test-asan-vk
    - .lava-sc7180-trogdor-kingoftown:arm64
    - .collabora-turnip-manual-rules
  timeout: 2h
  variables:
    DEQP_SUITE: freedreno-a618-vk-asan
    FLAKES_CHANNEL: "#freedreno-ci"
    FDO_CI_CONCURRENT: 2 # We get OOMkills if we go too wide with asan enabled

a618-gles-asan:
  extends:
    - .lava-arm64-test-asan-gl
    - .lava-sc7180-trogdor-kingoftown:arm64
    - .collabora-turnip-manual-rules
  variables:
    DEQP_SUITE: freedreno-a618-gles-asan
    FLAKES_CHANNEL: "#freedreno-ci"
    FDO_CI_CONCURRENT: 2 # We get OOMkills if we go too wide with asan enabled

# Run dEQP EGL window system tests with the window systems available.
# X11 takes over the screen, wayland is run headless.
a618-gl:
  extends:
    - .lava-arm64-test-gl
    - .lava-sc7180-trogdor-lazor-limozeen:arm64
    - .collabora-freedreno-rules
  variables:
    DEQP_SUITE: freedreno-a618
    FLAKES_CHANNEL: "#freedreno-ci"
    HWCI_START_XORG: 1
    HWCI_START_WESTON: 1
    DEQP_FRACTION: 4

a618-gl-full:
  extends:
    - a618-gl
    - .collabora-freedreno-manual-rules
  timeout: 65m
  variables:
    FDO_CI_CONCURRENT: 6  # More causes issues and slows the job down
    DEQP_FRACTION: 1

a618-skqp:
  extends:
    - .lava-arm64-test-gl
    - .lava-sc7180-trogdor-kingoftown:arm64
    - .collabora-freedreno-rules
    # SKQP tests both the GL and VK drivers.
    - .collabora-freedreno-turnip-rules
  variables:
    FLAKES_CHANNEL: "#freedreno-ci"
    HWCI_START_XORG: 1
    DEQP_SUITE: freedreno-a618-skqp

a618-piglit:
  extends:
    - .lava-arm64-test-gl
    - .lava-sc7180-trogdor-lazor-limozeen:arm64
    - .test-piglit
    # Note that piglit has GL+VK integration testing.
    - .collabora-freedreno-turnip-rules
  rules:
    - !reference [.collabora-freedreno-turnip-rules, rules]
    - !reference [.rusticl-rules, rules]
  variables:
    DEQP_SUITE: freedreno-a618-piglit
    FDO_CI_CONCURRENT: 6  # More causes issues and isn't much faster anyway
    FLAKES_CHANNEL: "#freedreno-ci"
    HWCI_START_WESTON: 1

a618-piglit-full:
  extends:
    - .lava-arm64-test-gl
    - .lava-sc7180-trogdor-kingoftown:arm64
    - .test-piglit
    # Note that piglit has GL+VK integration testing.
    - .collabora-freedreno-turnip-manual-rules
  timeout: 60m
  variables:
    DEQP_SUITE: freedreno-a618-piglit-full
    FLAKES_CHANNEL: "#freedreno-ci"
    HWCI_START_WESTON: 1

a618-traces:
  extends:
    - .lava-arm64-piglit-traces
    - .lava-sc7180-trogdor-kingoftown:arm64
    - .collabora-freedreno-rules
  variables:
    HWCI_START_WESTON: 1
    # So we aren't capped by VSync by the X server
    EGL_PLATFORM: surfaceless
    FDO_CI_CONCURRENT: 5  # 6 is too much leading to OOM
    FLAKES_CHANNEL: "#freedreno-ci"
    PIGLIT_REPLAY_DEVICE_NAME: "${GPU_VERSION}"
    # This lets us run several more traces which don't use any features we're
    # missing.
    MESA_GLSL_VERSION_OVERRIDE: "460"
    MESA_GL_VERSION_OVERRIDE: "4.6"
    PIGLIT_TRACES_FILE: traces-freedreno.yml

a618-traces-performance:
  extends:
    - a618-traces
    - .collabora-freedreno-rules-performance
    - .piglit-performance-base
  rules:
    - !reference [.piglit-performance-base, rules]
    - !reference [.collabora-freedreno-rules-performance, rules]
  variables:
    # Always use the same device
    # a618 tag starts with cbg-1 (not cbg-0) for some reason
    LAVA_TAGS: "cbg-1"

a660-angle:
  extends:
    - .lava-arm64-test-gl
    - .lava-sm8350-hdk:arm64
    - .collabora-turnip-manual-rules
    - .test-angle
  variables:
    DEQP_SUITE: tu-angle
    DRIVER_NAME: null  # Don't use freedreno skips

a660-gl-cl:
  extends:
    - .lava-arm64-test-gl
    - .lava-sm8350-hdk:arm64
    - .test-piglit
    - .collabora-freedreno-rules
  rules:
    - !reference [.collabora-freedreno-rules, rules]
    - !reference [.rusticl-rules, rules]
  parallel: 3
  variables:
    DEQP_SUITE: freedreno-a660
    HWCI_START_WESTON: 1

a660-vk:
  extends:
    - .lava-arm64-test-vk
    - .collabora-turnip-rules
    - .lava-sm8350-hdk:arm64
  parallel: 3
  variables:
    DEQP_SUITE: freedreno-a660-vk
    FLAKES_CHANNEL: "#freedreno-ci"
    DEQP_FRACTION: 6

a660-vk-full:
  extends:
    - a660-vk
    - .collabora-turnip-manual-rules
  parallel: 3
  timeout: 2h
  variables:
    DEQP_SUITE: freedreno-a660-vk-full
    DEQP_FRACTION: 1

a750-angle:
  extends:
    - .ci-tron-arm64-test-gl
    - .a750-mupuf
    - .valve-turnip-manual-rules
    - .test-angle
  timeout: 25m  # base runtime 10min total, 7min of testing
  variables:
    CI_TRON_TIMEOUT__OVERALL__MINUTES: 20
    DEQP_SUITE: tu-angle
    DRIVER_NAME: null  # Don't use freedreno skips

a750-gl-cl:
  extends:
    - .ci-tron-arm64-test-gl
    - .test-piglit
    - .a750-mupuf
    - .valve-freedreno-manual-rules
  rules:
    - !reference [.valve-freedreno-manual-rules, rules]
    - !reference [.rusticl-manual-rules, rules]
  timeout: 30m  # base runtime 11min total, 8min of testing
  variables:
    CI_TRON_TIMEOUT__OVERALL__MINUTES: 25
    HWCI_START_WESTON: 1
    DEQP_SUITE: freedreno-a750

a750-vk:
  extends:
    - .ci-tron-arm64-test-vk
    - .a750-mupuf
    - .valve-turnip-manual-rules
  timeout: 75m  # base runtime 54min total, 51min of testing
  variables:
    CI_TRON_TIMEOUT__OVERALL__MINUTES: 70
    DEQP_SUITE: freedreno-a750-vk

a750-vkd3d:
  extends:
    - .ci-tron-arm64-test-vk
    - .a750-mupuf
    - .valve-turnip-manual-rules
    - .test-vkd3d-proton
  timeout: 15m  # base runtime 3min
  variables:
    CI_TRON_TIMEOUT__OVERALL__MINUTES: 12
    FDO_CI_CONCURRENT: 1
