#ifndef R600_ATOMICS_H
#define R600_ATOMICS_H

#define CM_MAX_ATOMIC_COUNTERS 8

#define EG_MAX_ATOMIC_COUNTERS 8
#define EG_MAX_ATOMIC_BUFFERS 8

# if EG_MAX_ATOMIC_BUFFERS != EG_MAX_ATOMIC_COUNTERS
# error EG_MAX_ATOMIC_BUFFERS and EG_MAX_ATOMIC_COUNTERS
# endif
#endif
