#ifndef R600_ATOMICS_H
#define R600_ATOMICS_H

#define CM_MAX_ATOMIC_COUNTERS 4096

#define EG_MAX_ATOMIC_COUNTERS 12
#define EG_MAX_ATOMIC_BUFFERS 12

# if EG_MAX_ATOMIC_BUFFERS != EG_MAX_ATOMIC_COUNTERS
# error EG_MAX_ATOMIC_BUFFERS and EG_MAX_ATOMIC_COUNTERS
# endif
#endif
